### ISSUE TITLE
소스 오픈

### ISSUE THREAD

**Issue by lutics** [yjung0911/coffee_order#3]
- [ ] 그간 스터디 한 소스를 이 Repo에 Commit 해본다

**Comment by yjung0911** [comment]
이게 무슨의미야? visual studio code에서 하는거야?

**Comment by lutics** [comment]
소스를 커밋해보는 실습을 해보라는 의미였고

VSCode 에서도 가능하고 어려우면 Github Client 가 있으니 그걸로 뭔지라도 봐보고 어려우면 얘기하구 ㅎ
